apiVersion: v1
kind: Service
metadata:
  name: redis-slave
  labels:
    app: redis
    role: slave
    tier: backend
spec:
  ports:
  - name: redis
    port: 6379
  - name: metrics
    port: 9121
    targetPort: 9121
  selector:
    app: redis
    role: slave
    tier: backend
